version: "1"
name: "weather-api"
services:
  db:
    container_name: weather-postgres
    image: postgres:latest
    volumes: 
      - ./db:/docker-entrypoint-initdb.d:ro
      - dbdata:/var/lib/postgresql/dbdata
    environment:
      - POSTGRES_PASSWORD=password
  api:
    container_name: weather-api
    image: node:slim
    volumes:
      - type: bind
        source: ./
        target: /weather
    working_dir: /weather
    ports: 
      - 5000:3000
    environment:
      - PORT=3000
      - PGHOST=db
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=password
      - PGPORT=5432
    command: bash -c "npm install && npm run dev"
volumes:
  dbdata:
